### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by jamessetaro** [datacompboy/WavPlayer#13]
I get an error when trying to build:

WavPlayer blah$ haxe release.hxml
Player.hx:21: characters 49-50 : Unexpected ,

Do I need a specific version of haxe?

**Comment by jamessetaro** [comment]
I used haxe 2 and didn't use brew to install and it compiles fine now.

http://haxe.org/download/version/2.10.0/

**Comment by datacompboy** [comment]
Oh! Thank you, i'll update README and will try to update later to Haxe-3.
